extends SceneTree
func _initialize():
	print("CHECK_START")
	var w = load("res://scripts/world/world.gd")
	var p = load("res://scripts/player/player.gd")
	var e = load("res://scripts/world/enemy.gd")
	var a = load("res://scripts/autoload/audio_bus.gd")
	var j = load("res://scripts/ui/journal_panel.gd")
	var h = load("res://scripts/combat/hitsplat.gd")
	var hb = load("res://scripts/characters/humanoid_builder.gd")
	var mm = load("res://scripts/ui/minimap.gd")
	var np = load("res://scripts/ui/npc_panel.gd")
	var ts = load("res://scripts/ui/title_screen.gd")
	var pp = load("res://scripts/ui/parent_panel.gd")
	var gs = load("res://scripts/autoload/game_state.gd")
	print("LOADED", w!=null, p!=null, e!=null, a!=null, j!=null, h!=null, hb!=null, mm!=null, np!=null, ts!=null, pp!=null, gs!=null)
	var root = Node3D.new()
	root.name = "T"
	get_root().add_child(root)
	var parts = HumanoidBuilder.build(root)
	print("PARTS", parts.has("accessory"), parts.has("weapon"), parts.has("l_arm"))
	HumanoidBuilder.style_accessory(parts, {"id":"brass_lantern","name":"Brass Lantern","color":"#f4a261"})
	print("ACCESSORY_OK")
	HumanoidBuilder.style_hat(parts, {"id":"explorers_hat","name":"Explorer's Hat","color":"#5c4033"})
	print("HAT_OK", parts.get("hat") != null)
	HumanoidBuilder.style_hat(parts, {"id":"kindness_crownlet","name":"Kindness Crownlet","color":"#c9b037"})
	print("CROWN_OK")
	HumanoidBuilder.style_cloak(parts, {"id":"stewards_cloak","name":"Steward Cloak","color":"#6a4c93","defense":1})
	HumanoidBuilder.style_armor(parts, {"id":"stewards_cloak","name":"Steward Cloak","color":"#6a4c93","defense":1})
	print("CLOAK_ARMOR_OK")
	var plate: MeshInstance3D = parts.get("chest_plate")
	var jewel: MeshInstance3D = parts.get("hat_jewel")
	var weap: Node3D = parts.get("weapon")
	print("ARMOR_VISIBLE", plate != null and plate.visible)
	print("HAT_JEWEL_VISIBLE", jewel != null and jewel.visible)
	print("WEAPON_ON_ARM", weap != null and weap.get_parent() == parts.get("r_arm"))
	HumanoidBuilder.style_armor(parts, {"id":"default_cape","name":"Travel Cape","color":"#c1121f","defense":0})
	print("ARMOR_HIDDEN_NO_DEF", plate != null and not plate.visible)
	for mesh in ["sword", "axe", "staff", "bow", "dagger", "mallet"]:
		HumanoidBuilder.style_weapon(parts, {"id":"t_"+mesh,"name":mesh,"mesh":mesh,"color":"#a67c52"})
		print("WEAPON_", mesh.to_upper(), parts.get("weapon_mesh"), parts.get("blade")!=null)
	print("WORLD_SCRIPT", w != null)
	var gs_src = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("CONSUMABLE_API", "func use_consumable" in gs_src)
	print("PIN_RESET_API", "func reset_parent_pin_to_default" in gs_src)
	print("REPATH_API", "func _repath_around_blocker" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("INDOOR_NAV_API", "_setup_indoor_navigation" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var items_src = FileAccess.get_file_as_string("res://data/items.json")
	print("TRAIL_RATIONS", '"trail_rations"' in items_src)
	print("HONEY_CAKE", '"honey_cake"' in items_src)
	print("HEARTY_STEW", '"hearty_stew"' in items_src)
	var inv_src = FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd")
	print("LIVE_CD", "_cd_label_was" in inv_src)
	print("PATH_ASSIST_API", "Soft path assist" in FileAccess.get_file_as_string("res://scripts/player/player.gd") or "_stuck_timer" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("LOOKOUT_API", "_build_lookout_rock" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MILL_API", "_build_mill_bridge" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("NAV_API", "_setup_outdoor_navigation" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("PANTRY_API", "func refill_pantry" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	var gs2 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("BEST_FOOD_API", "func use_best_consumable" in gs2)
	print("FOUNTAIN_REST_API", "func rest_at_fountain" in gs2)
	print("AVOID_API", "_soft_avoid_entities" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("WASD_AVOID", "set_velocity_forced" in FileAccess.get_file_as_string("res://scripts/player/player.gd") and "_manual_move" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("PARENT_WEEK_BAR", "_week_progress_bar" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PARENT_TABS", "_ensure_campaign_tabs" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PEEK_FOOD", "func peek_best_consumable" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("WEAPON_AND_GATE", "both gates must pass" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("HEAL_SPLAT", "spawn_heal" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	print("HEADLESS_GUARD", "class_name HeadlessGuard" in FileAccess.get_file_as_string("res://scripts/util/headless_guard.gd"))
	print("PARENT_WEEK_ROWS", "_add_week_row" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("CLICK_MARKER", "_show_click_marker" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("FOOD_HEAL_TICK", "heal_tick.emit(gained)" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("FOOT_DUST", "_puff_foot_dust" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("LANDMARK_APPROACH", "_update_landmark_approach" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("STRONG_HIT", "strong_foe" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	print("KILL_FLASH", "_begin_kill_flash" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("PARENT_EXPAND_PERSIST", "set_parent_expanded_weeks" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("TRAVEL_HINT_MILL", "K Mill" in FileAccess.get_file_as_string("res://scenes/main.tscn"))
	print("LANDMARK_GREET", "func mark_landmark_greeted" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("SOFT_TRAVEL_NOTE", "note_soft_travel_arrival" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("CRIT_VARIANCE", "randi_range(-1, 1)" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("SPUR_DENSITY", "LookoutTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "MillTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("DEFENSE_API", "func get_defense" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("DISCOVERED_LANDMARKS", "discovered_landmarks" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("FIRST_TOAST", "first_toast" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("INCOMING_VARIANCE", "base_in" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") or "get_defense" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("KILL_FLASH_RESTORE", "_restore_kill_flash_colors" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("SPUR_DENSITY_W15", "GladeTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "GardenTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "RidgeTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("DEFENSE_BREAKDOWN", "func get_defense_breakdown" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("ARMOR_UX", "Soft armor" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and "Def +" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd"))
	print("AMBIENT_LIFE", "_build_ambient_life" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("HIT_PAUSE", "_play_hit_pause" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("HURT_VIGNETTE", "_update_hurt_vignette" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("CAPE_UNEQUIP_FIX", "Travel Cape" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "default_cape" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("CONSUMABLE_EQUIP_GUARD", "Food is used with Use" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	var items_def = FileAccess.get_file_as_string("res://data/items.json")
	print("MID_LATE_DEFENSE", '"year_champion_cloak"' in items_def and '"defense": 3' in items_def and '"kindness_crownlet"' in items_def)
	print("ARMOR_ICONS", "_make_slot_icon" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd"))
	print("VILLAGE_AMBIENT", "Village green" in FileAccess.get_file_as_string("res://scripts/world/world.gd") or "0.0, 0, 8.0" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("HUD_DEF", "Def %d" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") or "· Def" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("VIGNETTE_OFFSET_FIX", "v1.16 bugfix" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("DEFENSE_CAP7", '"cap": 7' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "clampi(raw, 0, 7)" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("LATE_WILDS_TUNE", '"briar_boar"' in FileAccess.get_file_as_string("res://data/enemies.json") and '"max_hp": 24' in FileAccess.get_file_as_string("res://data/enemies.json") and '"damage": 6' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("PLAZA_AMBIENT_DENSE", '"dense": true' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wave 18" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MOSS_BADGER", '"moss_badger"' in FileAccess.get_file_as_string("res://data/enemies.json") and "_build_badger" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e24"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("WAVE19_AMBIENT", "Guild hall doorsteps" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wilds spurs" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("VERSION_119", 'config/version="1.19.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("VERSION_120", 'config/version="1.20.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("VERSION_122", 'config/version="1.22.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("VERSION_121", 'config/version="1.21.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("HELD_WEAPON", "r_arm.add_child(weapon)" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("STYLE_HAT", "func style_hat" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("STYLE_CLOAK", "func style_cloak" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("STYLE_ARMOR", "func style_armor" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("CHEST_PLATE", parts.has("chest_plate") and parts.has("l_pad") and parts.has("r_shoulder"))
	print("CEDAR_STAG", '"cedar_stag"' in FileAccess.get_file_as_string("res://data/enemies.json") and "_build_stag" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e28"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("CEDAR_HOLLOW", "_build_cedar_hollow" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Cedar Hollow" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_O", "KEY_O" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "O Hollow" in FileAccess.get_file_as_string("res://scenes/main.tscn"))
	print("YARD_ANIMALS", '"hen"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"lamb"' in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("LOADOUT_ARMOR_ICONS", "SlotRows" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and "WornTitle" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and "SoftArmor" in FileAccess.get_file_as_string("res://scenes/main.tscn"))
	print("UNEQUIP_GUARD", "not equipped" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd"))
	print("YEAR_PROGRESS_API", "func get_year_progress_note" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "func get_quest_mastery_progress" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("PARENT_YEAR_MASTERY", "Year progress / quest mastery" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") or "quest mastery" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd").to_lower())
	print("JOURNAL_YEAR_LINE", "get_year_progress_note" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	print("WILLOW_BEND", "_build_willow_bend" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Willow Bend" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_P", "KEY_P" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "p willow" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("HIT_FLASH", "func _begin_hit_flash" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("WEAPON_REST_META", "rest_rx" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("ATTACK_WRIST", "wrist flick" in FileAccess.get_file_as_string("res://scripts/player/player.gd").to_lower() or "Wave 22" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("CAPE_SWAY", "cape.rotation.y" in FileAccess.get_file_as_string("res://scripts/player/player.gd") or "cape sway" in FileAccess.get_file_as_string("res://scripts/player/player.gd").to_lower())
	print("REED_POOL", "_build_reed_pool" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Reed Pool" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_Y", "KEY_Y" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "y reed" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("YEAR_CHIP", "_year_chip" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "func get_year_progress_percent" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("DAILY_REMINDER", "func maybe_daily_checkpoint_reminder" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "PIN 1234" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("PIN_DEFAULT", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_123", 'config/version="1.23.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("QUIET_CROSS", "_build_quiet_cross" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Quiet Cross" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_U", "KEY_U" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "u cross" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("AGGRO_RIM", "AggroRim" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") and "TorusMesh" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("CHUNKY_SIGN", "_add_chunky_sign" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("JOURNAL_RAID_STAR", "_is_friday_raid" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd") and "Friday Raid" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	print("WEEK_UNLOCK_PCT", "~%d%% of the year" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "of the year" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_124", 'config/version="1.24.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("STONE_ARCH", "_build_stone_arch" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Stone Arch" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_X", "KEY_X" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "x arch" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("FOUNTAIN_FX", "_play_fountain_restore_fx" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "FountainRestoreFx" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("FOOD_HEAL_TOAST", "healed +%d HP (now %d/%d)" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "healed +" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("PARENT_HELP_COUNT", "Needs help:" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") or "Needs Help —" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PROGRESS_TICKS", "quarter ticks" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") or "¦" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PIN_STILL_1234", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_125", 'config/version="1.25.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("AMBER_KNOLL", "_build_amber_knoll" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Amber Knoll" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_Z", "KEY_Z" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "z knoll" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("MINIMAP_ICONS", "_draw_landmark_icon" in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd") and '"icon": "knoll"' in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("COMPASS_LANDMARK_TICK", "_update_landmark_tick" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "LandmarkTick" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("UNEQUIP_TOAST", "Unequipped" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("DEF_HIT_FLASH", "_on_hurt_def_flash" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "softens the hit" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("WARDROBE_PREVIEW", "_refresh_preview" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd") and "PreviewRow" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd"))
	print("PIN_STILL_1234_W25", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_126", 'config/version="1.26.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("BIRCH_REST", "_build_birch_rest" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Birch Rest" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_6", "KEY_6" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "6 birch" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("DAY_NIGHT_AUDIO", "set_day_night_audio" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_day_birds_loop" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("WEATHER_CLOUDS", "WeatherClouds" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "_clouds.amount" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("NPC_IDLE_6", "% 6" in FileAccess.get_file_as_string("res://scripts/world/npc.gd"))
	print("QUEST_MASTERY_PCT", "Toward mastery" in FileAccess.get_file_as_string("res://scripts/ui/quest_panel.gd"))
	print("PIN_STILL_1234_W26", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W26", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_127", 'config/version="1.27.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("FERN_DELL", "_build_fern_dell" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Fern Dell" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_7", "KEY_7" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "7 fern" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("DOOR_GLOW_PULSE", "_update_door_glows" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "DoorWash" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("HITSPLAT_SCALE_POP", "Wave 27" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd") and "scale" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	print("FOOT_DUST_W27", "Wave 27" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("JOURNAL_CAMPAIGN", "_campaign_name" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd") and "Kindling the Lamps" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	print("PARENT_LAST_SESSION", "_format_last_session" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") and "Last session" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PIN_STILL_1234_W27", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W27", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MINIMAP_FERN", '"icon": "fern"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"fern"' in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd"))
	print("VERSION_128", 'config/version="1.28.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("HEATHER_HEATH", "_build_heather_heath" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Heather Heath" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_8", "KEY_8" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "8 heather" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("VILLAGE_DUSK_LAMPS", "_update_village_dusk_lamps" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "_village_lamp_lights" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("RAIN_SPLASH", "_setup_rain_splash" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "RainSplash" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("AGGRO_PULSE_W28", "Wave 28" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("SAVE_RENAME_HINT", "nickname" in FileAccess.get_file_as_string("res://scripts/ui/main.gd").to_lower() or "siblings" in FileAccess.get_file_as_string("res://scripts/ui/title_screen.gd").to_lower())
	print("SAVE_SWITCH_TOAST", "Switched to slot" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("PIN_STILL_1234_W28", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W28", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MINIMAP_HEATHER", '"icon": "heather"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"heather"' in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd"))
	print("VERSION_129", 'config/version="1.29.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("THISTLE_RISE", "_build_thistle_rise" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Thistle Rise" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_9", "KEY_9" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "9 thistle" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("TRAVEL_GROUPS", "Wilds landmarks" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "group" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("QUEST_VICTORY_SPARKLE", "_play_quest_victory_sparkle" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "quest_mastered" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("FOG_MIST_CUE", "_setup_fog_mist" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "FogMist" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("AGGRO_NAME_TOAST", "always name the foe" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") or "soft yellow ring means step back" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("HP_BAR_LOW_TIER", "Wave 29" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") and "0.55" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("MINIMAP_THISTLE", '"icon": "thistle"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"thistle"' in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd"))
	print("PIN_STILL_1234_W29", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W29", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_130", 'config/version="1.30.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("MAPLE_COPSE", "_build_maple_copse" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Maple Copse" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_0", "KEY_0" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "0 maple" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("WIND_LEAVES", "_setup_wind_leaves" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "WindLeaves" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MINIMAP_ARROW_W30", "Wave 30" in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd") and "outline_tip" in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd"))
	print("MINIMAP_MAPLE", '"icon": "maple"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"maple"' in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd"))
	print("PARENT_EXPORT_LINE", "get_parent_export_line" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "Copy line" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PARENT_WEEK_HIGHLIGHT", "Wave 30" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") and "★" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PIN_STILL_1234_W30", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W30", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_131", 'config/version="1.31.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("PINE_FOX", '"pine_fox"' in FileAccess.get_file_as_string("res://data/enemies.json") and "_build_fox" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e33"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("PLAZA_CAMPFIRE", "_build_plaza_campfire" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "PlazaCampfire" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("NPC_TALK_PROMPT", "_update_talk_prompt" in FileAccess.get_file_as_string("res://scripts/world/npc.gd") and "Talk (F)" in FileAccess.get_file_as_string("res://scripts/world/npc.gd"))
	print("TARGET_RETICLE", "_ensure_target_reticle" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") and "TargetReticle" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("JOURNAL_MASTER_STAR", "Mastered this week" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd") and "_count_week_mastered" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	print("PIN_STILL_1234_W31", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W31", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_132", 'config/version="1.32.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("OAK_HARE", '"oak_hare"' in FileAccess.get_file_as_string("res://data/enemies.json") and "_build_hare" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e38"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("CAMPFIRE_SPARKS", "CampfireSparks" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wave 32" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("YEAR_CHIP_PLATE", "YearChipPanel" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Year ·" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("TALK_MUSIC_DUCK", "set_talk_duck" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "set_talk_duck" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("PANTRY_HEAL_PREVIEW", "+%d HP" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and "[Def +" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd"))
	print("PIN_STILL_1234_W32", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W32", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_133", 'config/version="1.33.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("BIRCH_SQUIRREL", '"birch_squirrel"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_squirrel" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e43"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("SOFTER_RAIN", "Wave 33: softer rain mix" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_rain.volume_db = -34.0" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("CAMPFIRE_CRACKLE", "set_campfire_audio" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "CampfireCrackle" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "set_campfire_audio" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("SOFT_DEFEAT_TOAST", "rest safe at the village fountain" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NEAR_MISS_MASTERY", "Near miss — mastery" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NPC_QUEST_STAR", "★" in FileAccess.get_file_as_string("res://scripts/ui/npc_panel.gd") and "Wave 33" in FileAccess.get_file_as_string("res://scripts/ui/npc_panel.gd"))
	print("NO_DAY_CASH", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("PIN_STILL_1234_W33", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W33", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_134", 'config/version="1.34.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("ASPEN_OTTER", '"aspen_otter"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_otter" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e48"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("WIND_WHOOSH", "set_wind_audio" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "WindWhoosh" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "set_wind_audio" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("FOOD_CD_CLEAR", "Wait %.1fs" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Ready · V:" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("WARDROBE_FLOURISH", "_play_wardrobe_flourish" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd") and "Wave 34" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd"))
	print("LAST_TRAVEL_MARK", "last_travel_label" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "★ last" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "Soft travel —" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("PIN_STILL_1234_W34", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W34", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W34", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("VERSION_135", 'config/version="1.35.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("ELM_RACCOON", '"elm_raccoon"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_raccoon" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e53"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("FOOT_PITCH", "_play_foot_varied" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "Wave 35" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("HUD_HP_CLEAR", "HP %d / %d" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "_ensure_clear_hp_text" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("DUSK_FLICKER", "Wave 35: soft dusk lamp flicker" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("PARENT_HELP_BOLD", "WEEK %d" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") and "All clear — wonderful work together" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PIN_STILL_1234_W35", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W35", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W35", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("VERSION_136", 'config/version="1.36.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("HAZEL_HEDGEHOG", '"hazel_hedgehog"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_hedgehog" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e58"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("SWING_WHOOSH_W36", "_play_swing_varied" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "Wave 36" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("MINIMAP_ZOOM_W36", "Wave 36: clearer minimap zoom feel" in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd") and '"zoom": zoom' in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var jp36 = FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd")
	print("JOURNAL_MASTERY_PCT_W36", "get_latest_attempt_percent" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "Mastered ★" in jp36 and "—— Available" in jp36)
	print("PIN_STILL_1234_W36", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W36", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W36", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_137", 'config/version="1.37.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("WILLOW_WREN", '"willow_wren"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_wren" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e63"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("HALL_REVERB_W37", "set_hall_reverb" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "HallReverb" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "set_hall_reverb" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("LEAF_RUSTLE_W37", "set_leaf_rustle" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "LeafRustle" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_update_leaf_rustle" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("AGGRO_COUNTDOWN_W37", "~%.1fs to step back" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") and "_countdown_nudge" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	var inv37 = FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd")
	print("INV_SLOT_TAGS_W37", "SLOT_TAGS" in inv37 and "[Head]" in inv37 and "need Combat Lv" in inv37 and "Unequippable yet" in inv37)
	print("PIN_STILL_1234_W37", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W37", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W37", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_138", 'config/version="1.38.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("MAPLE_MOUSE", '"maple_mouse"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_mouse" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e68"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("BROOK_MURMUR_W38", "set_brook_murmur" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "BrookMurmur" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_update_brook_murmur" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("QUEST_CHIME_W38", "_quest_chime" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "Wave 38: clearer quest-complete chime" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("MUTE_CLEAR_W38", "Muted · M" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "_ensure_mute_styles" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("SAVE_CHIP_W38", "_ensure_save_chip" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Save ·" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Autosaved" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("PIN_STILL_1234_W38", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W38", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W38", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_139", 'config/version="1.39.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("SPRUCE_MOLE", '"spruce_mole"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_mole" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e73"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("DUSK_FIREFLIES_W39", "_setup_dusk_fireflies" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "_is_dusk_firefly_time" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "DuskFireflies" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("COMPASS_N_W39", "_ensure_clear_compass_n" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Wave 39: clearer compass N" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("PANTRY_EMPTY_W39", "fountain (H)" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "Wave 39: clearer empty pantry toast" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	var main39 = FileAccess.get_file_as_string("res://scripts/ui/main.gd")
	print("TRAVEL_SEARCH_W39", "_on_travel_filter_changed" in main39 and "_refresh_travel_list" in main39 and "Filter landmarks by name" in main39 and "group counts" in main39)
	print("PIN_STILL_1234_W39", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W39", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W39", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_140", 'config/version="1.40.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("BEECH_CHIPMUNK", '"beech_chipmunk"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_chipmunk" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e78"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("MILESTONE_TOAST_W40", "✦ Milestone · Week" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "unlocked_week % 5 == 0" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("LANDMARK_APPROACH_W40", "✦ New landmark" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "✦ Near ·" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("COMBAT_XP_FLOAT_W40", "spawn_xp" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd") and "spawn_xp" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") and 'kind == "xp"' in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	var pp40 = FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd")
	print("PARENT_PIN_TOAST_W40", "PIN changed successfully" in pp40 and "Parent PIN updated successfully" in pp40)
	print("CAMPAIGN_TAB_COUNTS_W40", "Wave 40: campaign tab shows mastered/total" in pp40 and "%s · %d/%d" in pp40)
	print("PIN_STILL_1234_W40", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W40", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W40", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_141", 'config/version="1.41.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("ALDER_DUCK", '"alder_duck"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_duck" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e83"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("PUDDLE_RIPPLES_W41", "_setup_rain_puddle_ripples" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "RainPuddleRipples" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("FIRST_FIGHT_TIP_W41", "First fight: soft ticks" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	var hud41 = FileAccess.get_file_as_string("res://scripts/ui/hud.gd")
	print("HP_COMBAT_LV_W41", "HP %d / %d · Lv %d" in hud41 and "Wave 41: combat level shown near HP" in hud41)
	print("FOOD_READY_FLASH_W41", "_food_ready_flash_t" in hud41 and "Wave 41: soft Ready flash" in hud41)
	print("PIN_STILL_1234_W41", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W41", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W41", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_142", 'config/version="1.42.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("FIR_FROG", '"fir_frog"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_frog" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e88"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("HALL_CHATTER_W42", "set_hall_chatter" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "HallChatter" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "set_hall_chatter" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("FOUNTAIN_GLOW_W42", "FountainRestoreGlow" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wave 42: clearer soft-defeat fountain glow" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("WARDROBE_SPARKLE_W42", "_play_wardrobe_equip_sparkle" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd") and "WardrobeEquipSparkle" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd"))
	var jp42 = FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd")
	print("JOURNAL_PROGRESS_W42", "_campaign_progress_fraction" in jp42 and "Week %d/36" in jp42 and "Friday Raid → NEXT" in jp42)
	print("PIN_STILL_1234_W42", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W42", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W42", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_143", 'config/version="1.43.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("CYPRESS_TURTLE", '"cypress_turtle"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_turtle" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e93"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("CRICKET_HUSH_W43", "_night_cricket_hush" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "Wave 43: soft night cricket hush" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("TRAVEL_FADE_W43", "_soft_travel_with_fade" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "SoftTravelFade" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("HIT_EDGE_SOFT_W43", "_hit_edge_flash_t" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Wave 43: soft brief screen-edge flash" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	var inv43 = FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd")
	print("INV_SORT_UNLOCK_W43", "SLOT_SORT" in inv43 and "_append_locked_gear_hints" in inv43 and "Unlock via quest" in inv43)
	print("PIN_STILL_1234_W43", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W43", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("NO_DAY_CASH_W43", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))

	print("VERSION_144", 'config/version="1.44.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("POPLAR_DOVE", '"poplar_dove"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_dove" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e98"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("DAWN_BIRD_SWELL_W44", "_apply_dawn_bird_swell" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "Wave 44: soft morning bird swell" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("WEATHER_CYCLE_TOAST_W44", "Weather cycle ·" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "bright open skies settle soft" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TALK_CAM_NUDGE_W44", "begin_talk_camera_nudge" in FileAccess.get_file_as_string("res://scripts/player/player.gd") and "_begin_talk_camera_nudge" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	var pp44 = FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd")
	var gs44 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PARENT_EXPORT_HELP_W44", "Needs help:" in gs44 and "_relative_session_age" in pp44)
	print("PIN_STILL_1234_W44", "const DEFAULT_PIN := \"1234\"" in gs44 or 'DEFAULT_PIN := "1234"' in gs44)
	print("MASTERY_80_W44", "MASTERY_PCT := 0.8" in gs44 or "0.8" in gs44)
	print("NO_DAY_CASH_W44", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))


	print("VERSION_145", 'config/version="1.45.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("ROWAN_ROBIN", '"rowan_robin"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_robin" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e103"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("CAMPFIRE_SMOKE_W45", "CampfireSmoke" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wave 31/32/33/45" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MUTE_TOAST_W45", "Muted · soft hush" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Unmuted · village sounds return" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("PULLBACK_SPARKLE_W45", "_leave_combat_soft" in FileAccess.get_file_as_string("res://scripts/player/player.gd") and "CombatPullbackSparkle" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	var main45 = FileAccess.get_file_as_string("res://scripts/ui/main.gd")
	print("TRAVEL_DIST_W45", "_travel_distance_label" in main45 and "~%d paces" in main45)
	var gs45 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W45", "const DEFAULT_PIN := \"1234\"" in gs45 or 'DEFAULT_PIN := "1234"' in gs45)
	print("MASTERY_80_W45", "MASTERY_PCT := 0.8" in gs45 or "0.8" in gs45)
	print("NO_DAY_CASH_W45", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))


	print("VERSION_146", 'config/version="1.46.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("ASH_SPARROW", '"ash_sparrow"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_sparrow" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e108"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("EDGE_FOG_W46", "_setup_edge_fog_banks" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "EdgeFogBanks" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("YEAR_CHIP_FLASH_W46", "_year_chip_flash_t" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "_apply_year_chip_flash" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("MASTERY_SPARKLE_W46", "QuestVictoryGlow" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wave 29/46" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var hud46 = FileAccess.get_file_as_string("res://scripts/ui/hud.gd")
	print("LANDMARK_CHIP_W46", "_ensure_landmark_chip" in hud46 and "landmark_name" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var gs46 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W46", "const DEFAULT_PIN := \"1234\"" in gs46 or 'DEFAULT_PIN := "1234"' in gs46)
	print("MASTERY_80_W46", "MASTERY_PCT := 0.8" in gs46 or "0.8" in gs46)
	print("NO_DAY_CASH_W46", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))


	print("VERSION_147", 'config/version="1.47.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("HICKORY_QUAIL", '"hickory_quail"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_quail" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e113"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("SNOWDUST_W47", "_setup_snowdust" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "ColdFogSnowdust" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("DOOR_WHOOSH_W47", "play_door_whoosh" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "play_door_whoosh" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var gs47 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("SOFT_DEFEAT_HP_W47", "+%d HP & pantry restored." in gs47 and "heal_tick.emit(restored)" in gs47)
	var jp47 = FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd")
	print("JOURNAL_CAMPAIGN_STARS_W47", "_count_campaign_mastered" in jp47 and "Campaign ★" in jp47 and "📌 Next raid" in jp47)
	print("PIN_STILL_1234_W47", "const DEFAULT_PIN := \"1234\"" in gs47 or 'DEFAULT_PIN := "1234"' in gs47)
	print("MASTERY_80_W47", "MASTERY_PCT := 0.8" in gs47 or "0.8" in gs47)
	print("NO_DAY_CASH_W47", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))


	print("VERSION_148", 'config/version="1.48.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("JUNIPER_JAY", '"juniper_jay"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_jay" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e118"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("CANOPY_DRIP_W48", "_setup_canopy_drip" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "RainCanopyDrip" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TARGET_NAMEPLATE_W48", "_update_target_nameplate" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("WARDROBE_CLOSE_W48", "_play_wardrobe_close_flourish" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd"))
	var gs48 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("EQUIP_TOAST_W48", "Equipped %s." in gs48)
	print("FOOD_STACK_W48", "stack %d/%d" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and '"%s %d/%d"' in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("PIN_STILL_1234_W48", "const DEFAULT_PIN := \"1234\"" in gs48 or 'DEFAULT_PIN := "1234"' in gs48)
	print("MASTERY_80_W48", "MASTERY_PCT := 0.8" in gs48 or "0.8" in gs48)
	print("NO_DAY_CASH_W48", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))


	print("VERSION_149", 'config/version="1.49.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("SYCAMORE_SKINK", '"sycamore_skink"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_skink" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e123"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("DUSK_OWL_W49", "_dusk_owl_hoot" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "DuskOwlHoot" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("TRAVEL_PUFF_W49", "_play_soft_travel_landing_puff" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "SoftTravelLandingPuff" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("FOOD_HEAL_SPARKLE_W49", "_play_food_heal_sparkle" in FileAccess.get_file_as_string("res://scripts/player/player.gd") and "FoodHealSparkle" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	var pp49 = FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd")
	print("NEEDS_HELP_HIGHLIGHT_W49", "Wave 49: highlight needs-help count when >0" in pp49 and "set_tab_tooltip" in pp49)
	var gs49 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W49", "const DEFAULT_PIN := \"1234\"" in gs49 or 'DEFAULT_PIN := "1234"' in gs49)
	print("MASTERY_80_W49", "MASTERY_PCT := 0.8" in gs49 or "0.8" in gs49)
	print("NO_DAY_CASH_W49", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))



	print("VERSION_150", 'config/version="1.50.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("CHESTNUT_TOAD", '"chestnut_toad"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_toad" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e128"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("FESTIVAL_SPARKLE_W50", "play_festival_decade_sparkle" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "maybe_festival_decade" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("SOFT_AGGRO_COMBO_W50", "Wave 50: clearer soft-aggro name+countdown combo" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("FOUNTAIN_MIST_W50", "FountainPlazaMist" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var hud50 = FileAccess.get_file_as_string("res://scripts/ui/hud.gd")
	print("FOE_COUNT_W50", "_ensure_foe_count" in hud50 and "Foes · %d" in hud50)
	print("WAVE50_TOAST", "maybe_wave_50_toast" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "maybe_wave_50_toast" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	var gs50 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W50", "const DEFAULT_PIN := \"1234\"" in gs50 or 'DEFAULT_PIN := "1234"' in gs50)
	print("MASTERY_80_W50", "MASTERY_PCT := 0.8" in gs50 or "0.8" in gs50)
	print("NO_DAY_CASH_W50", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))



	print("VERSION_151", 'config/version="1.51.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("WALNUT_WEASEL", '"walnut_weasel"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_weasel" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e133"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("EAVES_SPLASH_W51", "_setup_eaves_splash" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "RainEavesSplash" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("JOURNAL_FLOURISH_W51", "_play_journal_open_flourish" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	var hit51 = FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd")
	print("XP_FLOAT_SIZE_W51", "Wave 51" in hit51 and "amount >= 100" in hit51)
	var main51 = FileAccess.get_file_as_string("res://scripts/ui/main.gd")
	print("TRAVEL_FAV_W51", "PinFavBtn" in main51 and "_travel_pin_favorite" in main51 and "★ fav" in main51)
	print("WAVE51_TOAST", "maybe_wave_51_toast" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "maybe_wave_51_toast" in main51)
	var gs51 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W51", "const DEFAULT_PIN := \"1234\"" in gs51 or 'DEFAULT_PIN := "1234"' in gs51)
	print("MASTERY_80_W51", "MASTERY_PCT := 0.8" in gs51 or "0.8" in gs51)
	print("NO_DAY_CASH_W51", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))




	print("VERSION_152", 'config/version="1.52.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("PECAN_POSSUM", '"pecan_possum"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_possum" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e138"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("WIND_CHIME_W52", "set_wind_chime" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "HallWindChime" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_update_hall_wind_chime" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("DEFEAT_CAM_W52", "_play_soft_defeat_camera_settle" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("WARDROBE_PULSE_W52", "_play_wardrobe_preview_pulse" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd"))
	var jp52 = FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd")
	print("JOURNAL_QOL_W52", "OpenOnlyBtn" in jp52 and "_open_only" in jp52 and "weeks locked" in jp52)
	print("WAVE52_TOAST", "maybe_wave_52_toast" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "maybe_wave_52_toast" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	var gs52 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W52", "const DEFAULT_PIN := \"1234\"" in gs52 or 'DEFAULT_PIN := "1234"' in gs52)
	print("MASTERY_80_W52", "MASTERY_PCT := 0.8" in gs52 or "0.8" in gs52)
	print("NO_DAY_CASH_W52", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))




	print("VERSION_153", 'config/version="1.53.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("MAGNOLIA_BEAVER", '"magnolia_beaver"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_beaver" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e143"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("GARDEN_FIREFLIES_W53", "PrayerGardenFireflies" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "_setup_garden_fireflies" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MUTE_PULSE_W53", "_pulse_mute_plate" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("SOFT_PULL_COLOR_W53", "Wave 53: soft color shift yellow" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	var inv53 = FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd")
	print("BAG_DEF_W53", "Worn gear · Def %d" in inv53)
	print("READY_GLOW_W53", "Wave 53: stronger Ready glow" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") or "longer Ready bloom" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("WAVE53_TOAST", "maybe_wave_53_toast" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "maybe_wave_53_toast" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	var gs53 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W53", "const DEFAULT_PIN := \"1234\"" in gs53 or 'DEFAULT_PIN := "1234"' in gs53)
	print("MASTERY_80_W53", "MASTERY_PCT := 0.8" in gs53 or "0.8" in gs53)
	print("NO_DAY_CASH_W53", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))



	print("VERSION_154", 'config/version="1.54.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("OLIVE_OWL", '"olive_owl"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_owl" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e148"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("BROOK_SPARKLE_W54", "BrookSparkle" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "_setup_brook_sparkle" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_FLOURISH_W54", "_play_travel_open_flourish" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("NEAR_MISS_CHIME_W54", "play_quest_near_miss" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_quest_near_miss_chime" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "play_quest_near_miss" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	var pp54 = FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd")
	print("PIN_WRONG_TOAST_W54", "Wrong PIN" in pp54 and "Wave 54: clearer PIN wrong toast" in pp54)
	print("WAVE54_TOAST", "maybe_wave_54_toast" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "maybe_wave_54_toast" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	var gs54 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W54", "const DEFAULT_PIN := \"1234\"" in gs54 or 'DEFAULT_PIN := "1234"' in gs54)
	print("MASTERY_80_W54", "MASTERY_PCT := 0.8" in gs54 or "0.8" in gs54)
	print("NO_DAY_CASH_W54", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))




	print("VERSION_155", 'config/version="1.55.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("PALM_PIKA", '"palm_pika"' in FileAccess.get_file_as_string("res://data/enemies.json") and "static func _build_pika" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e153"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("EMBER_POP_W55", "play_ember_pop" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_ember_pop_sfx" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("YEAR_WEEK_FLASH_W55", "_year_chip_last_week" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Wave 55: clearer Year chip when week unlocks" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("DEFEAT_MIST_LINGER_W55", "Wave 55: soft-defeat mist linger" in FileAccess.get_file_as_string("res://scripts/world/world.gd") or "lifetime = 3.2" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("SAVE_SLOT_CHIP_W55", "Save · #%d · %s" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "Wave 55: show save slot number" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("WAVE55_TOAST", "maybe_wave_55_toast" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "maybe_wave_55_toast" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	var gs55 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("PIN_STILL_1234_W55", "const DEFAULT_PIN := \"1234\"" in gs55 or 'DEFAULT_PIN := "1234"' in gs55)
	print("MASTERY_80_W55", "MASTERY_PCT := 0.8" in gs55 or "0.8" in gs55)
	print("NO_DAY_CASH_W55", "day_cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower() and "Day Cash" not in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))



	print("CHECK_OK")
	quit(0)
