extends SceneTree
func _initialize():
	print("CHECK_START")
	var w = load("res://scripts/world/world.gd")
	var p = load("res://scripts/player/player.gd")
	var e = load("res://scripts/world/enemy.gd")
	var a = load("res://scripts/autoload/audio_bus.gd")
	var j = load("res://scripts/ui/journal_panel.gd")
	var h = load("res://scripts/combat/hitsplat.gd")
	var hb = load("res://scripts/characters/humanoid_builder.gd")
	var mm = load("res://scripts/ui/minimap.gd")
	var np = load("res://scripts/ui/npc_panel.gd")
	var ts = load("res://scripts/ui/title_screen.gd")
	var pp = load("res://scripts/ui/parent_panel.gd")
	var gs = load("res://scripts/autoload/game_state.gd")
	print("LOADED", w!=null, p!=null, e!=null, a!=null, j!=null, h!=null, hb!=null, mm!=null, np!=null, ts!=null, pp!=null, gs!=null)
	var root = Node3D.new()
	root.name = "T"
	get_root().add_child(root)
	var parts = HumanoidBuilder.build(root)
	print("PARTS", parts.has("accessory"), parts.has("weapon"), parts.has("l_arm"))
	HumanoidBuilder.style_accessory(parts, {"id":"brass_lantern","name":"Brass Lantern","color":"#f4a261"})
	print("ACCESSORY_OK")
	HumanoidBuilder.style_hat(parts, {"id":"explorers_hat","name":"Explorer's Hat","color":"#5c4033"})
	print("HAT_OK", parts.get("hat") != null)
	HumanoidBuilder.style_hat(parts, {"id":"kindness_crownlet","name":"Kindness Crownlet","color":"#c9b037"})
	print("CROWN_OK")
	HumanoidBuilder.style_cloak(parts, {"id":"stewards_cloak","name":"Steward Cloak","color":"#6a4c93","defense":1})
	HumanoidBuilder.style_armor(parts, {"id":"stewards_cloak","name":"Steward Cloak","color":"#6a4c93","defense":1})
	print("CLOAK_ARMOR_OK")
	var plate: MeshInstance3D = parts.get("chest_plate")
	var jewel: MeshInstance3D = parts.get("hat_jewel")
	var weap: Node3D = parts.get("weapon")
	print("ARMOR_VISIBLE", plate != null and plate.visible)
	print("HAT_JEWEL_VISIBLE", jewel != null and jewel.visible)
	print("WEAPON_ON_ARM", weap != null and weap.get_parent() == parts.get("r_arm"))
	HumanoidBuilder.style_armor(parts, {"id":"default_cape","name":"Travel Cape","color":"#c1121f","defense":0})
	print("ARMOR_HIDDEN_NO_DEF", plate != null and not plate.visible)
	for mesh in ["sword", "axe", "staff", "bow", "dagger", "mallet"]:
		HumanoidBuilder.style_weapon(parts, {"id":"t_"+mesh,"name":mesh,"mesh":mesh,"color":"#a67c52"})
		print("WEAPON_", mesh.to_upper(), parts.get("weapon_mesh"), parts.get("blade")!=null)
	print("WORLD_SCRIPT", w != null)
	var gs_src = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("CONSUMABLE_API", "func use_consumable" in gs_src)
	print("PIN_RESET_API", "func reset_parent_pin_to_default" in gs_src)
	print("REPATH_API", "func _repath_around_blocker" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("INDOOR_NAV_API", "_setup_indoor_navigation" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var items_src = FileAccess.get_file_as_string("res://data/items.json")
	print("TRAIL_RATIONS", '"trail_rations"' in items_src)
	print("HONEY_CAKE", '"honey_cake"' in items_src)
	print("HEARTY_STEW", '"hearty_stew"' in items_src)
	var inv_src = FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd")
	print("LIVE_CD", "_cd_label_was" in inv_src)
	print("PATH_ASSIST_API", "Soft path assist" in FileAccess.get_file_as_string("res://scripts/player/player.gd") or "_stuck_timer" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("LOOKOUT_API", "_build_lookout_rock" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MILL_API", "_build_mill_bridge" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("NAV_API", "_setup_outdoor_navigation" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("PANTRY_API", "func refill_pantry" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	var gs2 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("BEST_FOOD_API", "func use_best_consumable" in gs2)
	print("FOUNTAIN_REST_API", "func rest_at_fountain" in gs2)
	print("AVOID_API", "_soft_avoid_entities" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("WASD_AVOID", "set_velocity_forced" in FileAccess.get_file_as_string("res://scripts/player/player.gd") and "_manual_move" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("PARENT_WEEK_BAR", "_week_progress_bar" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PARENT_TABS", "_ensure_campaign_tabs" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PEEK_FOOD", "func peek_best_consumable" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("WEAPON_AND_GATE", "both gates must pass" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("HEAL_SPLAT", "spawn_heal" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	print("HEADLESS_GUARD", "class_name HeadlessGuard" in FileAccess.get_file_as_string("res://scripts/util/headless_guard.gd"))
	print("PARENT_WEEK_ROWS", "_add_week_row" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("CLICK_MARKER", "_show_click_marker" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("FOOD_HEAL_TICK", "heal_tick.emit(gained)" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("FOOT_DUST", "_puff_foot_dust" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("LANDMARK_APPROACH", "_update_landmark_approach" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("STRONG_HIT", "strong_foe" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	print("KILL_FLASH", "_begin_kill_flash" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("PARENT_EXPAND_PERSIST", "set_parent_expanded_weeks" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("TRAVEL_HINT_MILL", "K Mill" in FileAccess.get_file_as_string("res://scenes/main.tscn"))
	print("LANDMARK_GREET", "func mark_landmark_greeted" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("SOFT_TRAVEL_NOTE", "note_soft_travel_arrival" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("CRIT_VARIANCE", "randi_range(-1, 1)" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("SPUR_DENSITY", "LookoutTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "MillTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("DEFENSE_API", "func get_defense" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("DISCOVERED_LANDMARKS", "discovered_landmarks" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("FIRST_TOAST", "first_toast" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("INCOMING_VARIANCE", "base_in" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") or "get_defense" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("KILL_FLASH_RESTORE", "_restore_kill_flash_colors" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("SPUR_DENSITY_W15", "GladeTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "GardenTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "RidgeTrim" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("DEFENSE_BREAKDOWN", "func get_defense_breakdown" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("ARMOR_UX", "Soft armor" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and "Def +" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd"))
	print("AMBIENT_LIFE", "_build_ambient_life" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("HIT_PAUSE", "_play_hit_pause" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("HURT_VIGNETTE", "_update_hurt_vignette" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("CAPE_UNEQUIP_FIX", "Travel Cape" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "default_cape" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("CONSUMABLE_EQUIP_GUARD", "Food is used with Use" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	var items_def = FileAccess.get_file_as_string("res://data/items.json")
	print("MID_LATE_DEFENSE", '"year_champion_cloak"' in items_def and '"defense": 3' in items_def and '"kindness_crownlet"' in items_def)
	print("ARMOR_ICONS", "_make_slot_icon" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd"))
	print("VILLAGE_AMBIENT", "Village green" in FileAccess.get_file_as_string("res://scripts/world/world.gd") or "0.0, 0, 8.0" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("HUD_DEF", "Def %d" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") or "· Def" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("VIGNETTE_OFFSET_FIX", "v1.16 bugfix" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("DEFENSE_CAP7", '"cap": 7' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "clampi(raw, 0, 7)" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("LATE_WILDS_TUNE", '"briar_boar"' in FileAccess.get_file_as_string("res://data/enemies.json") and '"max_hp": 24' in FileAccess.get_file_as_string("res://data/enemies.json") and '"damage": 6' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("PLAZA_AMBIENT_DENSE", '"dense": true' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wave 18" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MOSS_BADGER", '"moss_badger"' in FileAccess.get_file_as_string("res://data/enemies.json") and "_build_badger" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e24"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("WAVE19_AMBIENT", "Guild hall doorsteps" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Wilds spurs" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("VERSION_119", 'config/version="1.19.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("VERSION_120", 'config/version="1.20.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("VERSION_122", 'config/version="1.22.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("VERSION_121", 'config/version="1.21.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("HELD_WEAPON", "r_arm.add_child(weapon)" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("STYLE_HAT", "func style_hat" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("STYLE_CLOAK", "func style_cloak" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("STYLE_ARMOR", "func style_armor" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("CHEST_PLATE", parts.has("chest_plate") and parts.has("l_pad") and parts.has("r_shoulder"))
	print("CEDAR_STAG", '"cedar_stag"' in FileAccess.get_file_as_string("res://data/enemies.json") and "_build_stag" in FileAccess.get_file_as_string("res://scripts/characters/creature_builder.gd") and '"id": "e28"' in FileAccess.get_file_as_string("res://data/enemies.json"))
	print("CEDAR_HOLLOW", "_build_cedar_hollow" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Cedar Hollow" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_O", "KEY_O" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "O Hollow" in FileAccess.get_file_as_string("res://scenes/main.tscn"))
	print("YARD_ANIMALS", '"hen"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"lamb"' in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("LOADOUT_ARMOR_ICONS", "SlotRows" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and "WornTitle" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd") and "SoftArmor" in FileAccess.get_file_as_string("res://scenes/main.tscn"))
	print("UNEQUIP_GUARD", "not equipped" in FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd"))
	print("YEAR_PROGRESS_API", "func get_year_progress_note" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "func get_quest_mastery_progress" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("PARENT_YEAR_MASTERY", "Year progress / quest mastery" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") or "quest mastery" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd").to_lower())
	print("JOURNAL_YEAR_LINE", "get_year_progress_note" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	print("WILLOW_BEND", "_build_willow_bend" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Willow Bend" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_P", "KEY_P" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "p willow" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("HIT_FLASH", "func _begin_hit_flash" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("WEAPON_REST_META", "rest_rx" in FileAccess.get_file_as_string("res://scripts/characters/humanoid_builder.gd"))
	print("ATTACK_WRIST", "wrist flick" in FileAccess.get_file_as_string("res://scripts/player/player.gd").to_lower() or "Wave 22" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("CAPE_SWAY", "cape.rotation.y" in FileAccess.get_file_as_string("res://scripts/player/player.gd") or "cape sway" in FileAccess.get_file_as_string("res://scripts/player/player.gd").to_lower())
	print("REED_POOL", "_build_reed_pool" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Reed Pool" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_Y", "KEY_Y" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "y reed" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("YEAR_CHIP", "_year_chip" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "func get_year_progress_percent" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("DAILY_REMINDER", "func maybe_daily_checkpoint_reminder" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") and "PIN 1234" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("PIN_DEFAULT", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_123", 'config/version="1.23.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("QUIET_CROSS", "_build_quiet_cross" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Quiet Cross" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_U", "KEY_U" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "u cross" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("AGGRO_RIM", "AggroRim" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd") and "TorusMesh" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("CHUNKY_SIGN", "_add_chunky_sign" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("JOURNAL_RAID_STAR", "_is_friday_raid" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd") and "Friday Raid" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	print("WEEK_UNLOCK_PCT", "~%d%% of the year" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "of the year" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_124", 'config/version="1.24.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("STONE_ARCH", "_build_stone_arch" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Stone Arch" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_X", "KEY_X" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "x arch" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("FOUNTAIN_FX", "_play_fountain_restore_fx" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "FountainRestoreFx" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("FOOD_HEAL_TOAST", "healed +%d HP (now %d/%d)" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "healed +" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("PARENT_HELP_COUNT", "Needs help:" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") or "Needs Help —" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PROGRESS_TICKS", "quarter ticks" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") or "¦" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PIN_STILL_1234", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_125", 'config/version="1.25.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("AMBER_KNOLL", "_build_amber_knoll" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Amber Knoll" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_Z", "KEY_Z" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "z knoll" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("MINIMAP_ICONS", "_draw_landmark_icon" in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd") and '"icon": "knoll"' in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("COMPASS_LANDMARK_TICK", "_update_landmark_tick" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "LandmarkTick" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("UNEQUIP_TOAST", "Unequipped" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("DEF_HIT_FLASH", "_on_hurt_def_flash" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd") and "softens the hit" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd"))
	print("WARDROBE_PREVIEW", "_refresh_preview" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd") and "PreviewRow" in FileAccess.get_file_as_string("res://scripts/ui/customize_screen.gd"))
	print("PIN_STILL_1234_W25", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_126", 'config/version="1.26.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("BIRCH_REST", "_build_birch_rest" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Birch Rest" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_6", "KEY_6" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "6 birch" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("DAY_NIGHT_AUDIO", "set_day_night_audio" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd") and "_day_birds_loop" in FileAccess.get_file_as_string("res://scripts/autoload/audio_bus.gd"))
	print("WEATHER_CLOUDS", "WeatherClouds" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "_clouds.amount" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("NPC_IDLE_6", "% 6" in FileAccess.get_file_as_string("res://scripts/world/npc.gd"))
	print("QUEST_MASTERY_PCT", "Toward mastery" in FileAccess.get_file_as_string("res://scripts/ui/quest_panel.gd"))
	print("PIN_STILL_1234_W26", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W26", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("VERSION_127", 'config/version="1.27.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("FERN_DELL", "_build_fern_dell" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Fern Dell" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_7", "KEY_7" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "7 fern" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("DOOR_GLOW_PULSE", "_update_door_glows" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "DoorWash" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("HITSPLAT_SCALE_POP", "Wave 27" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd") and "scale" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	print("FOOT_DUST_W27", "Wave 27" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("JOURNAL_CAMPAIGN", "_campaign_name" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd") and "Kindling the Lamps" in FileAccess.get_file_as_string("res://scripts/ui/journal_panel.gd"))
	print("PARENT_LAST_SESSION", "_format_last_session" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd") and "Last session" in FileAccess.get_file_as_string("res://scripts/ui/parent_panel.gd"))
	print("PIN_STILL_1234_W27", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W27", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MINIMAP_FERN", '"icon": "fern"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"fern"' in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd"))
	print("VERSION_128", 'config/version="1.28.0"' in FileAccess.get_file_as_string("res://project.godot"))
	print("HEATHER_HEATH", "_build_heather_heath" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "Heather Heath" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("TRAVEL_8", "KEY_8" in FileAccess.get_file_as_string("res://scripts/ui/main.gd") and "8 heather" in FileAccess.get_file_as_string("res://scripts/ui/hud.gd").to_lower())
	print("VILLAGE_DUSK_LAMPS", "_update_village_dusk_lamps" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "_village_lamp_lights" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("RAIN_SPLASH", "_setup_rain_splash" in FileAccess.get_file_as_string("res://scripts/world/world.gd") and "RainSplash" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("AGGRO_PULSE_W28", "Wave 28" in FileAccess.get_file_as_string("res://scripts/world/enemy.gd"))
	print("SAVE_RENAME_HINT", "nickname" in FileAccess.get_file_as_string("res://scripts/ui/main.gd").to_lower() or "siblings" in FileAccess.get_file_as_string("res://scripts/ui/title_screen.gd").to_lower())
	print("SAVE_SWITCH_TOAST", "Switched to slot" in FileAccess.get_file_as_string("res://scripts/ui/main.gd"))
	print("PIN_STILL_1234_W28", "const DEFAULT_PIN := \"1234\"" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or 'DEFAULT_PIN := "1234"' in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MASTERY_80_W28", "MASTERY_PCT := 0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd") or "0.8" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	print("MINIMAP_HEATHER", '"icon": "heather"' in FileAccess.get_file_as_string("res://scripts/world/world.gd") and '"heather"' in FileAccess.get_file_as_string("res://scripts/ui/minimap.gd"))
	print("CHECK_OK")
	quit(0)
