extends SceneTree
func _initialize():
	print("CHECK_START")
	var w = load("res://scripts/world/world.gd")
	var p = load("res://scripts/player/player.gd")
	var e = load("res://scripts/world/enemy.gd")
	var a = load("res://scripts/autoload/audio_bus.gd")
	var j = load("res://scripts/ui/journal_panel.gd")
	var h = load("res://scripts/combat/hitsplat.gd")
	var hb = load("res://scripts/characters/humanoid_builder.gd")
	var mm = load("res://scripts/ui/minimap.gd")
	var np = load("res://scripts/ui/npc_panel.gd")
	var ts = load("res://scripts/ui/title_screen.gd")
	var pp = load("res://scripts/ui/parent_panel.gd")
	var gs = load("res://scripts/autoload/game_state.gd")
	print("LOADED", w!=null, p!=null, e!=null, a!=null, j!=null, h!=null, hb!=null, mm!=null, np!=null, ts!=null, pp!=null, gs!=null)
	var root = Node3D.new()
	root.name = "T"
	get_root().add_child(root)
	var parts = HumanoidBuilder.build(root)
	print("PARTS", parts.has("accessory"), parts.has("weapon"), parts.has("l_arm"))
	HumanoidBuilder.style_accessory(parts, {"id":"brass_lantern","name":"Brass Lantern","color":"#f4a261"})
	print("ACCESSORY_OK")
	for mesh in ["sword", "axe", "staff", "bow", "dagger", "mallet"]:
		HumanoidBuilder.style_weapon(parts, {"id":"t_"+mesh,"name":mesh,"mesh":mesh,"color":"#a67c52"})
		print("WEAPON_", mesh.to_upper(), parts.get("weapon_mesh"), parts.get("blade")!=null)
	print("WORLD_SCRIPT", w != null)
	var gs_src = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("CONSUMABLE_API", "func use_consumable" in gs_src)
	print("PIN_RESET_API", "func reset_parent_pin_to_default" in gs_src)
	print("REPATH_API", "func _repath_around_blocker" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("INDOOR_NAV_API", "_setup_indoor_navigation" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	var items_src = FileAccess.get_file_as_string("res://data/items.json")
	print("TRAIL_RATIONS", '"trail_rations"' in items_src)
	var inv_src = FileAccess.get_file_as_string("res://scripts/ui/inventory_panel.gd")
	print("LIVE_CD", "_cd_label_was" in inv_src)
	print("PATH_ASSIST_API", "Soft path assist" in FileAccess.get_file_as_string("res://scripts/player/player.gd") or "_stuck_timer" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("LOOKOUT_API", "_build_lookout_rock" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("MILL_API", "_build_mill_bridge" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("NAV_API", "_setup_outdoor_navigation" in FileAccess.get_file_as_string("res://scripts/world/world.gd"))
	print("PANTRY_API", "func refill_pantry" in FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd"))
	var gs2 = FileAccess.get_file_as_string("res://scripts/autoload/game_state.gd")
	print("BEST_FOOD_API", "func use_best_consumable" in gs2)
	print("FOUNTAIN_REST_API", "func rest_at_fountain" in gs2)
	print("AVOID_API", "_soft_avoid_entities" in FileAccess.get_file_as_string("res://scripts/player/player.gd"))
	print("HEAL_SPLAT", "spawn_heal" in FileAccess.get_file_as_string("res://scripts/combat/hitsplat.gd"))
	print("CHECK_OK")
	quit(0)
